'use strict';
const DATA=window.AL_LIBRARY;
const $=id=>document.getElementById(id);
const PAGE_SIZE=60;
let faction='all',page=0,selectedCharacter=null,selectedSkin=null,app=null,sprite=null,loadedUrl=null,requestedUrl=null,loadToken=0,paused=false,baseScale=1;
const actionLabels={stand:'待机',stand2:'待机 2',normal:'日常',dance:'舞蹈',walk:'行走',move:'移动',move_left:'向左移动',attack:'攻击',attack_left:'向左攻击',skill:'技能',skill_start:'技能开始',skill_end:'技能结束',victory:'胜利',dead:'倒下',motou:'摸头',touch:'触摸',sit:'坐下',sleep:'睡觉',wash:'洗浴',yun:'眩晕',tuozhuai:'拖拽',tuozhuai2:'拖拽 2'};
function element(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el;}
function assetUrl(path){return path.split('/').map(encodeURIComponent).join('/');}
function skinCounts(character){const normal=character.skins.filter(s=>s.match==='exact').length;return normal?`${normal} 款皮肤`+(normal<character.skins.length?` · ${character.skins.length-normal} 项特殊素材`:''):`${character.skins.length} 项素材`;}
function renderFactions(){const nav=$('factions');nav.replaceChildren();for(const f of [{id:'all',name:'全部阵营',characters:DATA.characters.length},...DATA.factions]){const button=element('button',String(f.id)===String(faction)?'active':'');button.dataset.faction=f.id;button.append(element('span','',f.name),element('span','badge',f.characters));button.onclick=()=>{faction=f.id;page=0;renderFactions();renderRoles();};nav.append(button);}}
function filtered(){const q=$('search').value.trim().toLocaleLowerCase();const kind=$('kind').value;return DATA.characters.filter(c=>(faction==='all'||c.faction_id===Number(faction))&&(kind==='all'||c.kind===kind)&&(!q||(c.name+' '+c.prefab+' '+c.skins.map(s=>s.id+' '+s.name).join(' ')).toLocaleLowerCase().includes(q)));}
function renderRoles(){const roles=filtered();const pages=Math.ceil(roles.length/PAGE_SIZE);page=Math.min(page,Math.max(0,pages-1));$('heading').textContent=faction==='all'?'全部阵营':DATA.factions.find(f=>f.id===Number(faction)).name;$('count').textContent=`${roles.length} 个角色 / 分组 · ${roles.reduce((n,c)=>n+c.skins.length,0)} 项素材`;$('empty').hidden=roles.length>0;const grid=$('grid');grid.replaceChildren();for(const c of roles.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE)){const button=element('button','role');button.dataset.character=c.id;button.setAttribute('aria-label',`查看 ${c.name} 的皮肤`);const picture=element('div','picture');const img=element('img');img.src=assetUrl(c.preview);img.loading='lazy';img.alt=c.name;picture.append(img);const caption=element('div','caption');caption.append(element('h3','',c.name),element('p','',skinCounts(c)),element('p','faction',c.faction));button.append(picture,caption);button.onclick=()=>openCharacter(c);grid.append(button);}const nav=$('pagination');nav.replaceChildren();if(pages>1){const prev=element('button','','上一页');prev.disabled=page===0;prev.onclick=()=>{page--;renderRoles();};const next=element('button','','下一页');next.disabled=page===pages-1;next.onclick=()=>{page++;renderRoles();};nav.append(prev,element('span','',`${page+1} / ${pages}`),next);}}
function openCharacter(c){selectedCharacter=c;$('role-name').textContent=c.name;$('role-faction').textContent=c.faction;$('role-count').textContent=skinCounts(c);const list=$('skins');list.replaceChildren();for(const s of c.skins){const button=element('button','skin');button.dataset.skin=s.id;button.setAttribute('aria-label',`选择皮肤 ${s.name}`);const img=element('img');img.src=assetUrl(s.preview);img.loading='lazy';img.alt=s.name;const text=element('div');text.append(element('span','',s.name),element('small','',s.match==='exact'?(s.group_index===0?'默认皮肤':'皮肤'):(s.match==='variant'?'特殊动作 / 变体':'其他素材')));button.append(img,text);button.onclick=()=>loadSkin(s);list.append(button);}if(!$('detail').open)$('detail').showModal();ensurePlayer();loadSkin(c.skins[0]);}
function ensurePlayer(){if(app)return;app=new PIXI.Application({width:720,height:720,backgroundAlpha:0,preserveDrawingBuffer:true,antialias:true});app.view.setAttribute('aria-label','角色动作预览');$('stage').append(app.view);app.stop();}
function destroySprite(){app?.stop();if(app)app.ticker.remove(updateSprite);if(sprite){app.stage.removeChild(sprite);sprite.destroy({children:true,texture:false,baseTexture:false});sprite=null;}}
async function loadSkin(s){const token=++loadToken;selectedSkin=s;paused=false;$('pause').textContent='暂停';$('pause').disabled=true;$('animation').disabled=true;$('animation').replaceChildren();$('skin-name').textContent=s.name;$('skin-description').textContent=selectedCharacter.name+' · '+(s.match==='exact'?'皮肤':'特殊素材');$('folder').href=assetUrl(s.path)+'/';$('action-info').textContent='正在加载动作…';$('player-status').hidden=false;$('player-status').textContent=location.protocol==='file:'?'请双击“启动素材库.bat”，在本地素材库中播放动作。':'加载中…';for(const button of $('skins').children)button.classList.toggle('active',button.dataset.skin===s.id);destroySprite();if(location.protocol==='file:')return;const url=assetUrl(s.path+'/'+s.skel);requestedUrl=url;const old=loadedUrl;loadedUrl=null;try{if(old&&old!==url)await PIXI.Assets.unload(old);if(token!==loadToken)return;const resource=await PIXI.Assets.load(url);if(token!==loadToken){if(requestedUrl!==url)await PIXI.Assets.unload(url);return;}loadedUrl=url;sprite=new PIXI.spine.Spine(resource.spineData);sprite.autoUpdate=false;app.stage.addChild(sprite);app.ticker.add(updateSprite);const actions=sprite.spineData.animations;for(const action of actions)$('animation').add(new Option((actionLabels[action.name]||action.name)+' · '+action.name,action.name));const initial=['stand','normal','idle','walk'].find(n=>actions.some(a=>a.name===n))||actions[0]?.name;if(!initial)throw Error('该素材没有可播放的动作');$('animation').value=initial;$('animation').disabled=false;$('pause').disabled=false;$('player-status').hidden=true;setAction(initial);app.start();}catch(e){if(token!==loadToken)return;$('player-status').textContent='此素材暂时无法播放，请选择其他皮肤。';$('action-info').textContent=String(e);}}
function updateSprite(){if(sprite)sprite.update(app.ticker.deltaMS/1000);}
function fitAnimation(){let left=Infinity,top=Infinity,right=-Infinity,bottom=-Infinity;const track=sprite.state.getCurrent(0);const scale=sprite.state.timeScale;sprite.state.timeScale=1;for(let i=0;i<=48;i++){track.trackTime=track.animation.duration*i/48;sprite.update(0);const b=sprite.getLocalBounds();left=Math.min(left,b.x);top=Math.min(top,b.y);right=Math.max(right,b.x+b.width);bottom=Math.max(bottom,b.y+b.height);}sprite.state.timeScale=scale;track.trackTime=0;sprite.update(0);baseScale=Math.min(650/Math.max(1,right-left),650/Math.max(1,bottom-top),3);sprite.pivot.set((left+right)/2,(top+bottom)/2);sprite.position.set(360,360);$('zoom').value=100;sprite.scale.set(baseScale);}
function setAction(name){if(!sprite)return;sprite.skeleton.setToSetupPose();sprite.state.setAnimation(0,name,true).mixDuration=0;sprite.state.timeScale=Number($('speed').value);sprite.update(.01);fitAnimation();app.renderer.render(app.stage);$('action-info').textContent=`${sprite.spineData.animations.length} 个动作 · 循环播放 · `+(actionLabels[name]||name);}
function closePlayer(){loadToken++;destroySprite();if(app)app.ticker.remove(updateSprite);if(loadedUrl){const url=loadedUrl;loadedUrl=null;PIXI.Assets.unload(url).catch(()=>{});}selectedSkin=null;}
$('search').oninput=()=>{page=0;renderRoles();};$('kind').onchange=()=>{page=0;renderRoles();};$('close').onclick=()=>$('detail').close();$('detail').addEventListener('close',closePlayer);$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close();}});$('animation').onchange=()=>setAction($('animation').value);$('pause').onclick=()=>{paused=!paused;paused?app.stop():app.start();$('pause').textContent=paused?'播放':'暂停';};$('speed').onchange=()=>{if(sprite)sprite.state.timeScale=Number($('speed').value);};$('background').onchange=()=>{$('stage').className='stage '+$('background').value;};$('zoom').oninput=()=>{if(sprite){sprite.scale.set(baseScale*Number($('zoom').value)/100);app.renderer.render(app.stage);}};$('reset').onclick=()=>{if(sprite){fitAnimation();app.renderer.render(app.stage);}};
window.libraryApp={get sprite(){return sprite;},get character(){return selectedCharacter;},get skin(){return selectedSkin;},get paused(){return paused;}};
renderFactions();renderRoles();

