'use strict';
let battleApp=null,battleSprite=null,battleToken=0,battleLoaded=null,battlePaused=false,battleScale=1,pendingUnload=Promise.resolve();
const playerControls=el('div','player-controls');playerControls.hidden=true;
const action=el('select'),pauseButton=el('button','','暂停'),modeButton=el('button','','播放动作');modeButton.hidden=true;
const actionLabel=el('label','','动作');actionLabel.append(action);playerControls.append(actionLabel,pauseButton);$('picture').after(playerControls);$('images').before(modeButton);
const baseOpen=open;open=function(i){stopBattlePlayer();baseOpen(i);modeButton.hidden=!i.spine;modeButton.onclick=()=>playBattle(i);if(i.spine){$('status').textContent='原始 Spine 动作可在此直接播放；点击图片可查看原始透明贴图。'+(i.particle_systems?' Unity 粒子部分保留源数据，未在网页复现。':'');playBattle(i);}};
const baseSelect=select;select=function(i,p,n){if(battleSprite){battleApp?.stop();if(battleApp)battleApp.view.hidden=true;playerControls.hidden=true;}$('main-image').hidden=false;baseSelect(i,p,n);};
function updateBattle(){if(battleSprite)battleSprite.update(battleApp.ticker.deltaMS/1000);}
function stopBattlePlayer(){battleToken++;if(battleApp){battleApp.ticker.remove(updateBattle);battleApp.destroy(true,{children:true,texture:false,baseTexture:false});battleApp=null;}battleSprite=null;playerControls.hidden=true;if(battleLoaded){const old=battleLoaded;battleLoaded=null;pendingUnload=PIXI.Assets.unload(old).catch(()=>{});}}
async function playBattle(i){stopBattlePlayer();const token=++battleToken;$('image-info').textContent='正在加载原始动作…';try{await pendingUnload;if(token!==battleToken)return;const path=url(i.path+'/'+i.spine.skel),res=await PIXI.Assets.load(path);if(token!==battleToken)return;battleLoaded=path;battleApp=new PIXI.Application({width:720,height:520,backgroundAlpha:0,antialias:true,preserveDrawingBuffer:true});battleApp.view.setAttribute('aria-label','战斗素材动作预览');$('picture').append(battleApp.view);$('main-image').hidden=true;battleSprite=new PIXI.spine.Spine(res.spineData);battleSprite.autoUpdate=false;battleApp.stage.addChild(battleSprite);battleApp.ticker.add(updateBattle);action.replaceChildren();for(const a of battleSprite.spineData.animations)action.add(new Option(a.name,a.name));if(!action.options.length)throw Error('没有动作轨道');action.value=['stand','normal','idle','attack'].find(n=>[...action.options].some(o=>o.value===n))||action.options[0].value;setBattleAction();battlePaused=false;pauseButton.textContent='暂停';playerControls.hidden=false;}catch(e){$('image-info').textContent='动作暂时无法播放：'+String(e);}}
function setBattleAction(){if(!battleSprite)return;const s=battleSprite;s.skeleton.setToSetupPose();s.state.setAnimation(0,action.value,true).mixDuration=0;let left=Infinity,top=Infinity,right=-Infinity,bottom=-Infinity;const track=s.state.getCurrent(0);for(let n=0;n<=48;n++){track.trackTime=track.animation.duration*n/48;s.update(0);const b=s.getLocalBounds();left=Math.min(left,b.x);top=Math.min(top,b.y);right=Math.max(right,b.x+b.width);bottom=Math.max(bottom,b.y+b.height);}track.trackTime=0;s.update(0);s.pivot.set((left+right)/2,(top+bottom)/2);s.position.set(360,260);battleScale=Math.min(640/Math.max(1,right-left),440/Math.max(1,bottom-top),3);s.scale.set(battleScale);$('zoom').value=100;$('image-info').textContent=`${s.spineData.animations.length} 个原始动作 · ${action.value} · 循环播放`;}
action.onchange=setBattleAction;pauseButton.onclick=()=>{battlePaused=!battlePaused;battlePaused?battleApp.stop():battleApp.start();pauseButton.textContent=battlePaused?'播放':'暂停';};$('detail').addEventListener('close',stopBattlePlayer);
window.battlePlayer={get sprite(){return battleSprite;},get paused(){return battlePaused;}};
const imageZoom=$('zoom').oninput;$('zoom').oninput=()=>{imageZoom();if(battleSprite&&battleApp&&!battleApp.view.hidden){battleSprite.scale.set(battleScale*Number($('zoom').value)/100);battleApp.renderer.render(battleApp.stage);}};
