'use strict';
const DATA=window.AL_BATTLE,$=id=>document.getElementById(id);let category='炮弹',page=0;const SIZE=60;
function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e;}
function url(path){return path.split('/').map(encodeURIComponent).join('/');}
function nav(){$('categories').replaceChildren();for(const c of ['炮弹','飞机','鱼雷','飞机图标','其他战斗特效']){const b=el('button',c===category?'active':'');b.append(el('span','',c),el('span','badge',DATA.categories[c]||0));b.onclick=()=>{category=c;page=0;nav();render();};$('categories').append(b);}}
function render(){const q=$('search').value.trim().toLowerCase(),scope=$('scope').value;const rows=DATA.items.filter(i=>i.category===category&&(scope!=='visible'||i.has_preview)&&(scope!=='prefab'||i.prefab)&&(!q||(i.name+' '+i.model+' '+i.names.join(' ')).toLowerCase().includes(q)));const pages=Math.ceil(rows.length/SIZE);page=Math.min(page,Math.max(0,pages-1));$('heading').textContent=category;$('count').textContent=rows.length+' 项素材';$('empty').hidden=rows.length>0;$('grid').replaceChildren();for(const i of rows.slice(page*SIZE,(page+1)*SIZE)){const b=el('button','role');b.dataset.asset=i.id;const pic=el('div','picture');if(i.preview){const img=el('img');img.src=url(i.preview);img.alt=i.name;img.loading='lazy';pic.append(img);}else pic.append(el('span','no-image','原始特效资料'));const caption=el('div','caption');caption.append(el('h3','',i.name),el('p','',i.model),el('p','faction',i.category==='飞机图标'?'装备图标':i.particle_systems?'贴图 + Unity 粒子资料':i.prefab?'战斗素材':'贴图素材'));b.append(pic,caption);b.onclick=()=>open(i);$('grid').append(b);}$('pagination').replaceChildren();if(pages>1){const prev=el('button','','上一页'),next=el('button','','下一页');prev.disabled=!page;next.disabled=page>=pages-1;prev.onclick=()=>{page--;render();};next.onclick=()=>{page++;render();};$('pagination').append(prev,el('span','',`${page+1} / ${pages}`),next);}}
function open(i){$('category').textContent=i.category;$('name').textContent=i.name;$('model').textContent=i.model;$('images').replaceChildren();$('main-image').hidden=!i.images.length;$('image-info').textContent=i.images.length?'':'此项没有独立精灵图片，已保留原始预制体资料。';$('status').textContent=i.particle_systems?`包含 ${i.particle_systems} 个 Unity 粒子系统。此处查看原始贴图，完整粒子动画需在 Unity 中重建预制体并加载依赖。`:'图片可在此直接查看，保留透明背景。';$('native-info').textContent=`独立目录包含图片、asset.json 索引、prefab.json 组件数据和 source.bundle 原始包。${i.animations.length?`原始动画：${i.animations.join('、')}。`:''}`;$('aliases').textContent=i.names.slice(1,12).join(' · ');for(const [n,p] of i.images.entries()){const b=el('button');const img=el('img');img.src=url(i.path+'/'+p.file);img.alt=p.name||p.file;b.title=p.role+' · '+(p.name||'');b.append(img);b.onclick=()=>select(i,p,n);$('images').append(b);}if(i.images.length)select(i,i.images.find(p=>p.role==='战斗贴图')||i.images[0],i.images.findIndex(p=>p.role==='战斗贴图')<0?0:i.images.findIndex(p=>p.role==='战斗贴图'));$('detail').showModal();}
function select(i,p,n){$('main-image').src=url(i.path+'/'+p.file);$('main-image').alt=p.name||i.name;$('zoom').value=100;$('main-image').style.transform='scale(1)';$('image-info').textContent=`${p.name} · ${p.width} × ${p.height} · ${p.role}`;for(const [j,b] of [...$('images').children].entries())b.classList.toggle('active',j===n);}
$('search').oninput=()=>{page=0;render();};$('scope').onchange=()=>{page=0;render();};$('close').onclick=()=>$('detail').close();$('background').onchange=()=>$('picture').className='stage '+$('background').value;$('zoom').oninput=()=>$('main-image').style.transform=`scale(${$('zoom').value/100})`;nav();render();
